### ISSUE TITLE
opkg list-installed BUG?

### ISSUE THREAD

**Issue by BoostOver** [negan07/ancistrus#27] opened 2018-04-27 07:23 UTC
Trying 192.168.0.1...
Connected to 192.168.0.1.
Escape character is '^]'.
D7000 login: admin
Password:
admin@D7000:$ opkg list-installed
ancistrus-core - 1.0.4
hdparm - 9.52
network-test - 0.1.0-270
openssh - 7.6p1-010
qos-sqm - 1.2.0-13.027
smartmontools - 6.5
utelnetd - 0.1.11
zlib - 1.2.11
admin@D7000:$ opkg install iproute2
Package iproute2 (4.16.0) installed in root is up to date.
admin@D7000:$

**Comment by negan07** [comment] 2018-04-27 22:16
this happen when there's a half-broken install
try
`opkg install --force-reinstall iproute2`

**Comment by BoostOver** [comment] 2018-04-28 10:52
Trying 192.168.0.1...
Connected to 192.168.0.1.
Escape character is '^]'.
D7000 login: admin
Password:
admin@D7000:$ opkg clean
admin@D7000:$ opkg update
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/Packages.gz.
Updated source 'ancistrus-arm-D7000'.
admin@D7000:$ opkg install --force-reinstall iproute2
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/iproute2_4.16.0_armD7000.ipk.
Reinstalling iproute2 (4.16.0) on root.
Installing iproute2 (4.16.0) on root.
To remove package debris, try `opkg remove iproute2`.
To re-attempt the install, try `opkg install iproute2`.
Collected errors:
 * pkg_run_script: Internal error: iproute2 has a NULL tmp_unpack_dir.
 * prerm_upgrade_old_pkg: prerm script for package "iproute2" failed
 * opkg_solver_install: Cannot install package iproute2.
admin@D7000:$

**Comment by negan07** [comment] 2018-04-29 12:01
just a formalism: old iproute package has removal locked now locks has been removed to speedup upgrades like this

`rm /usr/lib/opkg/list/iproute2*`
`opkg update`
`opkg install iproute2`

**Comment by negan07** [comment] 2018-04-29 12:15
marked as duplicate of:

https://github.com/negan07/ancistrus/issues/28

close here and continue there

**Closed by negan07** 2018-04-29 12:15 UTC
Labels: duplicate, help wanted
