### ISSUE TITLE
QOS improvement

### ISSUE THREAD

**Issue by Matt-Mf** [negan07/ancistrus#73] opened 2020-05-31 23:09 UTC
Implement diffserv4 as PRIORITY QUEUE.

diffserv4 provides a general-purpose Diffserv implementation with four tins:
Bulk (CS1), 6.25% threshold, generally low priority.
Best Effort (general), 100% threshold.
Video (AF4x, AF3x, CS3, AF2x, CS2, TOS4, TOS1), 50% threshold.
Voice (CS7, CS6, EF, VA, CS5, CS4), 25% threshold.

**Comment by negan07** [comment] 2020-12-05 13:57
duplicate of:

https://github.com/negan07/ancistrus/issues/67

**Closed by negan07** 2020-12-05 13:57 UTC
Labels: enhancement, feature request
